### ISSUE TITLE
Double bottom padding when Keyboard appears on iOS

### ISSUE THREAD

**Issue by adamayoung** [driftyco/cordova-plugin-keyboard#136]
When the keyboard appears the web view resizes and the ion-content view adds keyboard-offset. Surely it should be one or the other?

This doesn't seem to be an issue with Android.

I've tried adding the following to config.xml but with no luck.

```
<preference name="KeyboardResizeMode" value="ionic" />
<preference name="KeyboardResize" value="false" />
```

![IMG_9398303D2D85-1](https://user-images.githubusercontent.com/2083536/70434371-ef851f80-1a7b-11ea-810e-93950b6b3566.jpeg)

![IMG_2C762AC6785C-1](https://user-images.githubusercontent.com/2083536/70434375-f4e26a00-1a7b-11ea-9e30-2cecb453fdd7.jpeg)

**Comment by oscar-gardiazabal** [comment]
You found the reason?
