### ISSUE TITLE
Can this plugin be used by non ionic apps, only pure Cordova apps ?

### ISSUE THREAD

**Issue by Aarbel** [driftyco/cordova-plugin-keyboard#137]
Can this plugin be used by non ionic apps, only pure Cordova apps ? 

I ask this question because the original repo (cjpearson/cordova-plugin-keyboard) is not maintained

Thanks a lot for your help

**Comment by nopol10** [comment]
Yes it can

**Comment by Aarbel** [comment]
ok looks great
